version: '3.8'

services:
  distml-app:
    build: .
    ports:
      - "8000:8000"
      - "8265:8265"  # Ray Dashboard
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEBUG=false
      - RAY_ADDRESS=auto
      - MAX_WORKERS=4
      - MAX_CONCURRENT_TASKS=10
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
